### PR TITLE
[REVIEW] Recompute `columns_to_hash` in DistributeAggregationKernel

### LINKED ISSUE #1327: [BUG] Coalesce in distributed mode (nRALS=2) produces wrong results
**Describe the bug**
The following coalesceTest queries produces wrong results with nRALS = 2.

```
queryId = "TEST_06"
query = """select SUM(COALESCE(n2.n_nationkey, 100)),
        COUNT(DISTINCT(COALESCE(n1.n_nationkey,32))),
        n2.n_regionkey as n1key from nation as n1
        full outer join nation as n2
        on n1.n_nationkey = n2.n_nationkey + 6
        GROUP BY n2.n_regionkey"""

queryId = 'TEST_09'
query = """select SUM(COALESCE(n2.n_nationkey, 100)),
      COUNT(DISTINCT(COALESCE(n1.n_nationkey,32))),
      COALESCE(n2.n_regionkey, 100) as n1key from nation as n1
      full outer join nation as n2
      on n1.n_nationkey = n2.n_nationkey + 6
      GROUP BY COALESCE(n2.n_regionkey, 100)"""
```
Current log:
```
ERROR: Different values

==============================
Coalesce
==============================
select SUM(COALESCE(n2.n_nationkey, 100)),
                    COUNT(DISTINCT(COALESCE(n1.n_nationkey,32))),
                    n2.n_regionkey as n1key from nation as n1
                    full outer join nation as n2
                    on n1.n_nationkey = n2.n_nationkey + 6
                    GROUP BY n2.n_regionkey

=============== New query: TEST_06 - parquet =================
                           #BLZ:                                                                                                                   
   EXPR$0  EXPR$1  n1key   
0    47.0     5.0    1.0
1    50.0     5.0    0.0
1    58.0     5.0    4.0
2    68.0     5.0    2.0
0    77.0     4.0    3.0
3   600.0     6.0    NaN
#DRILL:
   EXPR$0  EXPR$1  n1key
1    47.0     5.0    1.0
0    50.0     5.0    0.0
2    58.0     5.0    4.0
4    68.0     5.0    2.0
3    77.0     3.0    3.0
5   600.0     6.0    NaN
TEST_06 Test Coalesce - parquet
#QUERY:
select SUM(COALESCE(n2.n_nationkey, 100)),
                    COUNT(DISTINCT(COALESCE(n1.n_nationkey,32))),
                    n2.n_regionkey as n1key from nation as n1
                    full outer join nation as n2
                    on n1.n_nationkey = n2.n_nationkey + 6
                    GROUP BY n2.n_regionkey
RESULT:
ERROR:
Different values
Fail
TOTAL TIME: 
541.649341583252
CRASHED NODES: 
TOTAL NODES: 
===================================================
select SUM(COALESCE(n2.n_nationkey, 100)),
                  COUNT(DISTINCT(COALESCE(n1.n_nationkey,32))),
                  COALESCE(n2.n_regionkey, 100) as n1key from nation as n1
                  full outer join nation as n2
                  on n1.n_nationkey = n2.n_nationkey + 6
                  GROUP BY COALESCE(n2.n_regionkey, 100)

=============== New query: TEST_09 - parquet =================
                           #BLZ:                                                                                                                   
   EXPR$0  EXPR$1  n1key   
0    47.0     5.0    1.0
1    50.0     5.0    0.0
0    58.0     5.0    4.0
2    68.0     5.0    2.0
1    77.0     4.0    3.0
2   600.0     6.0  100.0
#DRILL:
   EXPR$0  EXPR$1  n1key
1    47.0     5.0    1.0
0    50.0     5.0    0.0
2    58.0     5.0    4.0
4    68.0     5.0    2.0
3    77.0     3.0    3.0
5   600.0     6.0  100.0
TEST_09 Test Coalesce - parquet
#QUERY:
select SUM(COALESCE(n2.n_nationkey, 100)),
                  COUNT(DISTINCT(COALESCE(n1.n_nationkey,32))),
                  COALESCE(n2.n_regionkey, 100) as n1key from nation as n1
                  full outer join nation as n2
                  on n1.n_nationkey = n2.n_nationkey + 6
                  GROUP BY COALESCE(n2.n_regionkey, 100)
RESULT:
ERROR:
Different values
Fail
TOTAL TIME: 
415.5755043029785
CRASHED NODES: 
TOTAL NODES: 
===================================================
```

**Expected behavior**
The above queries should generate a right output.

**Environment overview**
 - Environment location: Bare-metal
 - Method of cuDF install: conda nightly branch-0.19
 - Method of BSQL install: From source, nightly branch-0.19

### PR DESCRIPTION
**Pull request by Christian8491**
This PR closes #1327

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

File: engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.cpp [hunk 1]
```diff
@@ -129,7 +129,11 @@ ral::execution::task_result DistributeAggregateKernel::do_process(std::vector< s
     // num_partitions = context->getTotalNodes() will do for now, but may want a function to determine this in the future.
     // If we do partition into something other than the number of nodes, then we have to use part_ids and change up more of the logic
     int num_partitions = this->context->getTotalNodes();
-    
+
+    // we want to update the `columns_to_hash` because the input could have more columns after ComputeAggregateKernel
+    std::tie(columns_to_hash, std::ignore, std::ignore, std::ignore) = ral::operators::modGroupByParametersPostComputeAggregations(group_column_indices,
```
Comment (williamBlazing) [inline engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.cpp:134]: please move this to where you originally get these parameters. WHere you call `parseGroupByExpression` so that you only call it once and so that the group by parameters to be used by the kernel are these modified ones

**Review by williamBlazing — CHANGES_REQUESTED** [review]

File: engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.cpp (hunk 1 above)
Comment (Christian8491) [reply engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.cpp:134]: `parseGroupByExpression` is never used in the `DistributionAggregationKernel`.

Comment (Christian8491) [reply engine/src/execution_graph/logic_controllers/BatchAggregationProcessing.cpp]: done!
