### PR TITLE
[REVIEW] Parquet workaround for reading consecutive rowgroups

### LINKED ISSUE #463: [BUG] Blazing sql provides inconsisten JOIN results when having a table registered in parquet vs GPU
**Describe the bug**
Here's the following investigation notebook:
https://github.com/alexsisu/blazingsql_examples/blob/master/Parquet_Investigation.ipynb

Basically we have a table created on top of a cudf dataframe and a table (same data) create from a parquet file.
When performing the count(distinct) on the given table I get to separate results.
Please see the output[38] and output[39] in the linked notebook.

Also when performing a join I got 2 different types of results if a table is registered in parquet vs gpu.
Please see the last 2 cell outputs.
Please observe the nulls occuring in the last output cell of the notebook, which are not present in the previous output cell.

**Environment**

`printenv` result:

```
ROJ_LIB=/datadisk/miniconda3/envs/rapids2/share/proj
JAVA_LD_LIBRARY_PATH=/datadisk/miniconda3/envs/rapids2/jre/lib/amd64/server
SHELL=/bin/bash
TERM=xterm-256color
CONDA_SHLVL=2
CONDA_PROMPT_MODIFIER=(rapids2)
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
SUDO_USER=ubuntu
CONDA_EXE=/datadisk/miniconda3/bin/conda
SUDO_UID=1000
USERNAME=root
_CE_CONDA=
CONDA_PREFIX_1=/datadisk/miniconda3
CPL_ZIP_ENCODING=UTF-8
MAIL=/var/mail/root
PATH=/datadisk/miniconda3/envs/rapids2/bin:/datadisk/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
CONDA_PREFIX=/datadisk/miniconda3/envs/rapids2
PWD=/datadisk/work/blazing_poc
JAVA_HOME=/datadisk/miniconda3/envs/rapids2
LANG=en_US.UTF-8
GDAL_DATA=/datadisk/miniconda3/envs/rapids2/share/gdal
_CE_M=
SHLVL=1
SUDO_COMMAND=/bin/bash
HOME=/home/ubuntu
LC_TERMINAL_VERSION=3.3.9
CONDA_PYTHON_EXE=/datadisk/miniconda3/bin/python
LOGNAME=root
LC_CTYPE=UTF-8
JAVA_HOME_CONDA_BACKUP=
CONDA_DEFAULT_ENV=rapids2
LESSOPEN=| /usr/bin/lesspipe %s
SUDO_GID=1000
LC_TERMINAL=iTerm2
JAVA_LD_LIBRARY_PATH_BACKUP=
LESSCLOSE=/usr/bin/lesspipe %s %s
OLDPWD=/datadisk/work
_=/usr/bin/printenv

```

blazing and rapids libraries:
```
blazingsql                0.13.0a         cuda10.1_py37_267    blazingsql-nightly/label/cuda10.1
bsql-rapids-thirdparty    0.13.0                        3    blazingsql-nightly
bsql-toolchain            0.13.0                        3    blazingsql-nightly
bsql-toolchain-aws-cpp    0.13.0                        3    blazingsql-nightly
bsql-toolchain-gcp-cpp    0.13.0                        3    blazingsql-nightly

bsql-rapids-thirdparty    0.13.0                        3    blazingsql-nightly
cudf                      0.13.0a200316         py37_4041    rapidsai-nightly
cugraph                   0.13.0a200316          py37_374    rapidsai-nightly
cuml                      0.13.0a200316   cuda10.1_py37_1445    rapidsai-nightly
cuspatial                 0.13.0a200207            py37_7    rapidsai-nightly
dask-cuda                 0.13.0b200316           py37_69    rapidsai-nightly
dask-cudf                 0.13.0a200316         py37_4041    rapidsai-nightly
dask-xgboost              0.2.0.dev28      cuda10.1py36_0    rapidsai-nightly
libcudf                   0.13.0a200316     cuda10.1_4041    rapidsai-nightly
libcugraph                0.13.0a200316      cuda10.1_374    rapidsai-nightly
libcuml                   0.13.0a200316     cuda10.1_1445    rapidsai-nightly
libcumlprims              0.13.0a200313       cuda10.1_11    rapidsai-nightly
libcuspatial              0.13.0a200316       cuda10.1_19    rapidsai-nightly
libnvstrings              0.13.0a200316     cuda10.1_4041    rapidsai-nightly
librmm                    0.13.0a200316      cuda10.1_546    rapidsai-nightly
libxgboost                1.0.2dev.rapidsai0.13      cuda10.1_5    rapidsai-nightly
nvstrings                 0.13.0a200316         py37_4041    rapidsai-nightly
py-xgboost                1.0.2dev.rapidsai0.13  cuda10.1py37_5    rapidsai-nightly
rapids                    0.13.0          cuda10.1_py37_116    rapidsai-nightly
rapids-xgboost            0.13.0          cuda10.1_py37_116    rapidsai-nightly
rmm                       0.13.0a200316          py37_546    rapidsai-nightly
ucx                       1.7.0+g9d06c3a       cuda10.1_0    rapidsai-nightly
ucx-py                    0.13.0a200315+g9d06c3a         py37_69    rapidsai-nightly
xgboost                   1.0.2dev.rapidsai0.13  cuda10.1py37_5    rapidsai-nightly

```

### PR DESCRIPTION
**Pull request by rommelDB**
This is a temporary workaround that fixes #463

### CODE REVIEW

File: engine/src/io/data_parser/ParquetParser.cpp [hunk 1]
```diff
@@ -97,8 +97,10 @@ std::unique_ptr<ral::frame::BlazingTable> parquet_parser::parse(
 			consecutive_row_group_length.push_back(length_count);
 
 			if (consecutive_row_group_start.size() == 1){
```
Comment (williamBlazing) [inline engine/src/io/data_parser/ParquetParser.cpp]: QUeremos quitar este if else completamente. QUeremos hacer que siempre solo lea todo
