### PR TITLE
[WIP] Fix/vector result tables

### LINKED ISSUE #637: [BUG] Run query error, when handling very large dataframes with strings
**Describe the bug**
On a dask environment, Blazingsql throws an error when handling very large dataframes with strings even when it has enough GPU memory to store the output.

```
Traceback (most recent call last):
  File "script.py", line 203, in <module>
    result = main(bc)
  File "script.py", line 151, in main
    result_df = bc.sql(query_1)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 1651, in sql
    result = dask.dataframe.from_delayed(dask_futures)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/dask/dataframe/io/io.py", line 561, in from_delayed
    meta = delayed(make_meta)(dfs[0]).compute()
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/client.py", line 2595, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/client.py", line 1894, in gather
    asynchronous=asynchronous,
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/client.py", line 778, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/distributed/client.py", line 1753, in _gather
    raise exception.with_traceback(traceback)
  File "/home/rommelDB/miniconda3/envs/bsql-14/lib/python3.7/site-packages/pyblazing/apiv2/context.py", line 213, in collectPartitionsRunQuery
    config_options)
  File "bsql_engine/io/io.pyx", line 258, in cio.runQueryCaller
  File "bsql_engine/io/io.pyx", line 361, in cio.runQueryCaller
  File "bsql_engine/io/io.pyx", line 95, in cio.runQueryPython
cio.RunQueryError: [RunQuery Error] cuDF failure at: /conda/conda-bld/libcudf_1588271093864/work/cpp/src/strings/copying/concatenate.cu:232: total size of strings is too large for cudf column
```
**Steps/Code to reproduce bug**
ToDo

**Expected behavior**
No error should be thrown because data fits in local and distributed memory.

**Environment overview**
 - Environment location: Bare-metal
 - Method of cuDF install: conda nightly
 - Method of blazingsql install: sources branch-0.14

### PR DESCRIPTION
**Pull request by rommelDB**
Fixes #637

### CODE REVIEW

**Comment by kharoc** [comment]
1 RAL

========================================================
FAILED TESTS                                                                                                                                                                                                
========================================================                                                                                                                                                    
                        TestGroup InputType Result                                           TestId
0  Bindable Alias                  orc       Fail   TEST_09                                        
1  Date                            orc       Fail   TEST_01                                        
2  Simple Distribution From Local  orc       Fail   TEST_22,TEST_43,TEST_46,TEST_49                
3  TPCH Queries                    orc       Fail   TEST_03,TEST_05,TEST-08,TEST_10,TEST_14,TEST_18
4  Timestamp                       orc       Fail   TEST_02                                        
*******************************************************************************
TOTAL SUMMARY for test suite: 
PASSED: 1261/1274
FAILED: 13/1274
CRASH: 0/1274
TOTAL: 1274
MAX DELTA: 210.0
*******************************************************************************
Aggregations without group by:   Start Mem: 437.875   End Mem: 559.875   Diff: 122.0
Coalesce:   Start Mem: 559.875   End Mem: 613.875   Diff: 54.0
Column Basis:   Start Mem: 613.875   End Mem: 613.875   Diff: 0.0
Common Table Expressions:   Start Mem: 613.875   End Mem: 575.875   Diff: -38.0
Count without group by:   Start Mem: 575.875   End Mem: 583.875   Diff: 8.0
Date:   Start Mem: 583.875   End Mem: 581.875   Diff: -2.0
Timestamp:   Start Mem: 581.875   End Mem: 665.875   Diff: 84.0
Full outer join:   Start Mem: 665.875   End Mem: 663.875   Diff: -2.0
Group by:   Start Mem: 663.875   End Mem: 663.875   Diff: 0.0
Group by without aggregations:   Start Mem: 663.875   End Mem: 643.875   Diff: -20.0
Inner join:   Start Mem: 643.875   End Mem: 719.875   Diff: 76.0
Left outer join:   Start Mem: 719.875   End Mem: 707.875   Diff: -12.0
Non-EquiJoin Queries:   Start Mem: 707.875   End Mem: 823.875   Diff: 116.0
Nested Queries:   Start Mem: 823.875   End Mem: 741.875   Diff: -82.0
Order by:   Start Mem: 741.875   End Mem: 835.875   Diff: 94.0
Predicates With Nulls:   Start Mem: 835.875   End Mem: 773.875   Diff: -62.0
Simple String:   Start Mem: 773.875   End Mem: 795.875   Diff: 22.0
Unary ops:   Start Mem: 991.875   End Mem: 967.875   Diff: -24.0
Unify Tables:   Start Mem: 967.875   End Mem: 1059.875   Diff: 92.0
Union:   Start Mem: 1059.875   End Mem: 1005.875   Diff: -54.0
Limit:   Start Mem: 1005.875   End Mem: 1045.875   Diff: 40.0
Where clause:   Start Mem: 1045.875   End Mem: 1041.875   Diff: -4.0
Bindable Alias:   Start Mem: 1041.875   End Mem: 1177.875   Diff: 136.0
Boolean:   Start Mem: 1177.875   End Mem: 1115.875   Diff: -62.0
Case:   Start Mem: 1115.875   End Mem: 1157.875   Diff: 42.0
Cast:   Start Mem: 1157.875   End Mem: 1251.875   Diff: 94.0
Concat:   Start Mem: 1251.875   End Mem: 1315.875   Diff: 64.0
Literal:   Start Mem: 1315.875   End Mem: 1425.875   Diff: 110.0
Dir:   Start Mem: 1425.875   End Mem: 1523.875   Diff: 98.0
File System Local:   Start Mem: 1523.875   End Mem: 1389.875   Diff: -134.0
File System S3:   Start Mem: 1389.875   End Mem: 1433.875   Diff: 44.0
File System Google Storage :   Start Mem: 1433.875   End Mem: 1417.875   Diff: -16.0
Like:   Start Mem: 1417.875   End Mem: 1517.875   Diff: 100.0
Substring:   Start Mem: 1723.875   End Mem: 1701.875   Diff: -22.0
Wild Card:   Start Mem: 1701.875   End Mem: 1769.875   Diff: 68.0
TPCH Queries:   Start Mem: 1769.875   End Mem: 1979.875   Diff: 210.0
Round:   Start Mem: 1979.875   End Mem: 1925.875   Diff: -54.0


2 Worker's

========================================================
FAILED TESTS                                                                                                                                                                                                
========================================================                                                                                                                                                    
                        TestGroup InputType Result                                           TestId
0  Bindable Alias                  orc       Fail   TEST_09                                        
1  Date                            orc       Fail   TEST_01                                        
2  Simple Distribution From Local  orc       Fail   TEST_22,TEST_43,TEST_46,TEST_49                
3  TPCH Queries                    orc       Fail   TEST_03,TEST_05,TEST-08,TEST_10,TEST_14,TEST_18
4  Timestamp                       orc       Fail   TEST_02                                        
*******************************************************************************
TOTAL SUMMARY for test suite: 
PASSED: 1500/1513
FAILED: 13/1513
CRASH: 0/1513
TOTAL: 1513
MAX DELTA: 485.0
*******************************************************************************
Aggregations without group by:   Start Mem: 864.875   End Mem: 1349.875   Diff: 485.0
Coalesce:   Start Mem: 1349.875   End Mem: 1491.875   Diff: 142.0
Common Table Expressions:   Start Mem: 1491.875   End Mem: 1389.875   Diff: -102.0
Count without group by:   Start Mem: 1389.875   End Mem: 1445.875   Diff: 56.0
Date:   Start Mem: 1445.875   End Mem: 1479.875   Diff: 34.0
Timestamp:   Start Mem: 1479.875   End Mem: 1491.875   Diff: 12.0
Full outer join:   Start Mem: 1491.875   End Mem: 1491.875   Diff: 0.0
Group by:   Start Mem: 1491.875   End Mem: 1549.875   Diff: 58.0
Group by without aggregations:   Start Mem: 1549.875   End Mem: 1535.875   Diff: -14.0
Inner join:   Start Mem: 1535.875   End Mem: 1631.875   Diff: 96.0
Left outer join:   Start Mem: 1631.875   End Mem: 1697.875   Diff: 66.0
Non-EquiJoin Queries:   Start Mem: 1697.875   End Mem: 1673.875   Diff: -24.0
Nested Queries:   Start Mem: 1673.875   End Mem: 1765.875   Diff: 92.0
Order by:   Start Mem: 1765.875   End Mem: 1891.875   Diff: 126.0
Predicates With Nulls:   Start Mem: 1891.875   End Mem: 1937.875   Diff: 46.0
Simple String:   Start Mem: 1937.875   End Mem: 2009.875   Diff: 72.0
Unary ops:   Start Mem: 2313.875   End Mem: 2317.875   Diff: 4.0
Unify Tables:   Start Mem: 2317.875   End Mem: 2333.875   Diff: 16.0
Union:   Start Mem: 2333.875   End Mem: 2297.875   Diff: -36.0
Limit:   Start Mem: 2297.875   End Mem: 2073.875   Diff: -224.0
Where clause:   Start Mem: 2073.875   End Mem: 2097.875   Diff: 24.0
Bindable Alias:   Start Mem: 2097.875   End Mem: 2215.875   Diff: 118.0
Boolean:   Start Mem: 2215.875   End Mem: 2263.875   Diff: 48.0
Case:   Start Mem: 2263.875   End Mem: 2275.875   Diff: 12.0
Cast:   Start Mem: 2275.875   End Mem: 2395.875   Diff: 120.0
Concat:   Start Mem: 2395.875   End Mem: 2451.875   Diff: 56.0
Literal:   Start Mem: 2451.875   End Mem: 2513.875   Diff: 62.0
Dir:   Start Mem: 2513.875   End Mem: 2739.875   Diff: 226.0
File System Local:   Start Mem: 2739.875   End Mem: 2715.875   Diff: -24.0
File System S3:   Start Mem: 2715.875   End Mem: 2715.875   Diff: 0.0
File System Google Storage :   Start Mem: 2715.875   End Mem: 2805.875   Diff: 90.0
Like:   Start Mem: 2805.875   End Mem: 3097.875   Diff: 292.0
Substring:   Start Mem: 3339.875   End Mem: 3299.875   Diff: -40.0
Wild Card:   Start Mem: 3299.875   End Mem: 3487.875   Diff: 188.0
TPCH Queries:   Start Mem: 3487.875   End Mem: 3691.875   Diff: 204.0
Round:   Start Mem: 3691.875   End Mem: 3793.875   Diff: 102.0

File: engine/src/execution_graph/logic_controllers/CacheMachine.cpp [hunk 1]
```diff
@@ -319,6 +355,20 @@ ConcatenatingCacheMachine::ConcatenatingCacheMachine(size_t bytes_max_size)
 {
 }
 
+bool checkStrings(std::vector<std::unique_ptr<ral::frame::BlazingTable>> & holder_samples, CacheData & cache_data){
+	if(holder_samples.size()>=1){
+		for(int i=0;i<holder_samples[0]->view().num_columns();i++){
```
Comment (williamBlazing) [inline engine/src/execution_graph/logic_controllers/CacheMachine.cpp:360]: Add some checks here to make sure that all tables have the same number of columns. THat way in case that is not the case we can raise an error and not get a segfault.

Also, please rename this function. `checkStrings` is not very informative. It should be more like `checkIfConcatenatingStringsWillOverflowStringLength` or `checkIfCumulativeStringSizeIsTooBig` and please add an explanation for what the function does and what it should return

File: engine/src/execution_graph/logic_controllers/CacheMachine.cpp [hunk 2]
```diff
@@ -7,6 +7,40 @@
 namespace ral {
 namespace cache {
 
+cudf::size_type get_string_size(cudf::column_view column){
```
Comment (williamBlazing) [inline engine/src/execution_graph/logic_controllers/CacheMachine.cpp:10]: please add a quick function description

File: engine/src/execution_graph/logic_controllers/CacheMachine.cpp [hunk 3]
```diff
@@ -7,6 +7,40 @@
...
+			}
+
+			return total_size;
+		}
+	}
+
+	return 0;
+}
+
+std::vector<cudf::size_type> get_string_sizes(ral::frame::BlazingTableView table){
```
Comment (williamBlazing) [inline engine/src/execution_graph/logic_controllers/CacheMachine.cpp:33]: please add a quick function description

File: engine/bsql_engine/io/io.pyx [hunk 4]
```diff
@@ -243,9 +243,13 @@ cpdef parseMetadataCaller(fileList, offset, schema, file_format_hint, args):
...
-    df = cudf.DataFrame(CudfXxTable.from_unique_ptr(blaz_move(dereference(resultSet).cudfTable), decoded_names)._data)
-    df._rename_columns(decoded_names)    
-    return df
+    dfs = []
+    for i in range(dereference(resultSet).cudfTables.size()):
+      df = cudf.DataFrame(CudfXxTable.from_unique_ptr(blaz_move(dereference(resultSet).cudfTables[i]), decoded_names)._data)
+      df._rename_columns(decoded_names)
+      dfs.append(df)
+
+    return dfs[0]
```
Comment (williamBlazing) [inline engine/bsql_engine/io/io.pyx:252]: We are expecting that parseMetadataPython only returns a single partition. We should add an assert somewhere here. We are implicitliy expecting that with this `return dfs[0]` we should add an assert to make it safer

File: engine/bsql_engine/io/io.pyx [hunk 5]
```diff
@@ -433,8 +441,12 @@ cpdef runSkipDataCaller(table, queryPy):
       for i in range(names.size()):
           decoded_names.append(names[i].decode('utf-8'))
 
-      df = cudf.DataFrame(CudfXxTable.from_unique_ptr(blaz_move(dereference(resultSet).cudfTable), decoded_names)._data)
-      return_object['metadata'] = df 
+      dfs = []
+      for i in range(dereference(resultSet).cudfTables.size()):
+        dfs.append(cudf.DataFrame(CudfXxTable.from_unique_ptr(blaz_move(dereference(resultSet).cudfTables[i]), decoded_names)._data))
+
+      return_object['metadata'] = dfs
```
Comment (williamBlazing) [inline engine/bsql_engine/io/io.pyx:448]: `runSkipDataPython`, much like `parseMetadataPython` are expected to only return one partition. We should add an assert here for that and what this function returns should be the same as it was before. Lets not make this more complicated than it needs to by making it fix the same multi-partition output as `runQueryCaller`

File: pyblazing/pyblazing/apiv2/context.py [hunk 6]
```diff
@@ -1390,18 +1394,19 @@ def _optimize_with_skip_data_getSlices(self, current_table, scan_table_query,sin
...
-                grouped = file_and_rowgroup_indices.groupby('file_handle_index')
-                for group_id in grouped.groups:
-                    row_indices = grouped.groups[group_id].values.tolist()
-                    actual_files.append(current_table.files[group_id])
-                    if group_id < len(current_table.uri_values):
-                        uri_values.append(current_table.uri_values[group_id])
-                    row_groups_col = file_and_rowgroup_indices['row_group_index'].values.tolist()
-                    row_group_ids = [row_groups_col[i] for i in row_indices]
-                    row_groups_ids.append(row_group_ids)
+            for file_indices_and_rowgroup_indices_item in file_indices_and_rowgroup_indices:
```
Comment (williamBlazing) [inline pyblazing/pyblazing/apiv2/context.py:1397]: We should make `runSkipDataCaller` return the same as it used to and not implement all these changes here. We are always expecting the output to have one partition. This code which assumes otherwise just makes things more complicated

File: engine/src/execution_graph/logic_controllers/CacheMachine.cpp (hunk 1 above)
Comment (rommelDB) [reply engine/src/execution_graph/logic_controllers/CacheMachine.cpp]: I renamed the function and added some checks.

File: engine/src/execution_graph/logic_controllers/CacheMachine.cpp (hunk 2 above)
Comment (rommelDB) [reply engine/src/execution_graph/logic_controllers/CacheMachine.cpp:12]: I added the quick description.

File: engine/src/execution_graph/logic_controllers/CacheMachine.cpp (hunk 3 above)
Comment (rommelDB) [reply engine/src/execution_graph/logic_controllers/CacheMachine.cpp:36]: I added the quick description.

File: engine/bsql_engine/io/io.pyx (hunk 4 above)
Comment (rommelDB) [reply engine/bsql_engine/io/io.pyx]: I removed that code. The modifications now are only for the runQuery function.

File: engine/bsql_engine/io/io.pyx (hunk 5 above)
Comment (rommelDB) [reply engine/bsql_engine/io/io.pyx]: I removed that code. The modifications now are only for the runQuery function.

File: pyblazing/pyblazing/apiv2/context.py (hunk 6 above)
Comment (rommelDB) [reply pyblazing/pyblazing/apiv2/context.py]: I removed that code. The modifications now are only for the runQuery function.

**Comment by kharoc** [comment]
1 RAL

========================================================
FAILED TESTS                                                                                                                                                                                                
========================================================                                                                                                                                                    
                        TestGroup InputType Result                                           TestId
0  Bindable Alias                  orc       Fail   TEST_09                                        
1  Date                            orc       Fail   TEST_01                                        
2  Simple Distribution From Local  orc       Fail   TEST_22,TEST_43,TEST_46,TEST_49                
3  TPCH Queries                    orc       Fail   TEST_03,TEST_05,TEST-08,TEST_10,TEST_14,TEST_18
4  Timestamp                       orc       Fail   TEST_02                                        
*******************************************************************************
TOTAL SUMMARY for test suite: 
PASSED: 1261/1274
FAILED: 13/1274
CRASH: 0/1274
TOTAL: 1274
MAX DELTA: 48.0
*******************************************************************************
Aggregations without group by:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Coalesce:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Column Basis:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Common Table Expressions:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Count without group by:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Date:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Timestamp:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Full outer join:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Group by:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Group by without aggregations:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Inner join:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Left outer join:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Non-EquiJoin Queries:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Nested Queries:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Order by:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Predicates With Nulls:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Simple String:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Unary ops:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Unify Tables:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Union:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Limit:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Where clause:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Bindable Alias:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Boolean:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Case:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Cast:   Start Mem: 8117.875   End Mem: 8117.875   Diff: 0.0
Concat:   Start Mem: 8117.875   End Mem: 8165.875   Diff: 48.0
Literal:   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0
Dir:   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0
File System Local:   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0
File System S3:   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0
File System Google Storage :   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0
Like:   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0
Substring:   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0
Wild Card:   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0
TPCH Queries:   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0
Round:   Start Mem: 8165.875   End Mem: 8165.875   Diff: 0.0

2 Worker's

========================================================
FAILED TESTS                                                                                                                                                                                                
========================================================                                                                                                                                                    
                         TestGroup  InputType Result                                           TestId
0   Bindable Alias                  dask_cudf  Fail   TEST_08                                        
1   Bindable Alias                  gdf        Fail   TEST_08                                        
2   Bindable Alias                  orc        Fail   TEST_08,TEST_09                                
3   Bindable Alias                  parquet    Fail   TEST_08                                        
4   Bindable Alias                  psv        Fail   TEST_08                                        
5   Date                            orc        Fail   TEST_01                                        
6   Limit                           dask_cudf  Fail   TEST_07                                        
7   Limit                           gdf        Fail   TEST_07                                        
8   Limit                           orc        Fail   TEST_07                                        
9   Limit                           parquet    Fail   TEST_07                                        
10  Limit                           psv        Fail   TEST_07                                        
11  Simple Distribution From Local  dask_cudf  Fail   TEST_43                                        
12  Simple Distribution From Local  gdf        Fail   TEST_43                                        
13  Simple Distribution From Local  orc        Fail   TEST_22,TEST_43,TEST_46,TEST_49                
14  Simple Distribution From Local  parquet    Fail   TEST_43                                        
15  Simple Distribution From Local  psv        Fail   TEST_43                                        
16  TPCH Queries                    orc        Fail   TEST_03,TEST_05,TEST-08,TEST_10,TEST_14,TEST_18
17  Timestamp                       orc        Fail   TEST_02                                        
18  Union                           dask_cudf  Fail   TEST_01                                        
19  Union                           gdf        Fail   TEST_01                                        
20  Union                           orc        Fail   TEST_01                                        
21  Union                           parquet    Fail   TEST_01                                        
22  Union                           psv        Fail   TEST_01                                        
*******************************************************************************
TOTAL SUMMARY for test suite: 
PASSED: 1481/1513
FAILED: 32/1513
CRASH: 0/1513
TOTAL: 1513
MAX DELTA: 455.0
*******************************************************************************
Aggregations without group by:   Start Mem: 864.875   End Mem: 1319.875   Diff: 455.0
Coalesce:   Start Mem: 1319.875   End Mem: 1387.875   Diff: 68.0
Common Table Expressions:   Start Mem: 1387.875   End Mem: 1393.875   Diff: 6.0
Count without group by:   Start Mem: 1393.875   End Mem: 1403.875   Diff: 10.0
Date:   Start Mem: 1403.875   End Mem: 1483.875   Diff: 80.0
Timestamp:   Start Mem: 1483.875   End Mem: 1483.875   Diff: 0.0
Full outer join:   Start Mem: 1483.875   End Mem: 1483.875   Diff: 0.0
Group by:   Start Mem: 1483.875   End Mem: 1541.875   Diff: 58.0
Group by without aggregations:   Start Mem: 1541.875   End Mem: 1547.875   Diff: 6.0
Inner join:   Start Mem: 1547.875   End Mem: 1591.875   Diff: 44.0
Left outer join:   Start Mem: 1591.875   End Mem: 1621.875   Diff: 30.0
Non-EquiJoin Queries:   Start Mem: 1621.875   End Mem: 1727.875   Diff: 106.0
Nested Queries:   Start Mem: 1727.875   End Mem: 1765.875   Diff: 38.0
Order by:   Start Mem: 1765.875   End Mem: 1841.875   Diff: 76.0
Predicates With Nulls:   Start Mem: 1841.875   End Mem: 1969.875   Diff: 128.0
Simple String:   Start Mem: 1969.875   End Mem: 2033.875   Diff: 64.0
Unary ops:   Start Mem: 2307.875   End Mem: 2305.875   Diff: -2.0
Unify Tables:   Start Mem: 2305.875   End Mem: 2307.875   Diff: 2.0
Union:   Start Mem: 2307.875   End Mem: 2271.875   Diff: -36.0
Limit:   Start Mem: 2271.875   End Mem: 2067.875   Diff: -204.0
Where clause:   Start Mem: 2067.875   End Mem: 2093.875   Diff: 26.0
Bindable Alias:   Start Mem: 2093.875   End Mem: 2169.875   Diff: 76.0
Boolean:   Start Mem: 2169.875   End Mem: 2201.875   Diff: 32.0
Case:   Start Mem: 2201.875   End Mem: 2297.875   Diff: 96.0
Cast:   Start Mem: 2297.875   End Mem: 2349.875   Diff: 52.0
Concat:   Start Mem: 2349.875   End Mem: 2505.875   Diff: 156.0
Literal:   Start Mem: 2505.875   End Mem: 2511.875   Diff: 6.0
Dir:   Start Mem: 2511.875   End Mem: 2863.875   Diff: 352.0
File System Local:   Start Mem: 2863.875   End Mem: 2691.875   Diff: -172.0
File System S3:   Start Mem: 2691.875   End Mem: 2769.875   Diff: 78.0
File System Google Storage :   Start Mem: 2769.875   End Mem: 2847.875   Diff: 78.0
Like:   Start Mem: 2847.875   End Mem: 3099.875   Diff: 252.0
Substring:   Start Mem: 3369.875   End Mem: 3401.875   Diff: 32.0
Wild Card:   Start Mem: 3401.875   End Mem: 3589.875   Diff: 188.0
TPCH Queries:   Start Mem: 3589.875   End Mem: 3825.875   Diff: 236.0
Round:   Start Mem: 3825.875   End Mem: 3885.875   Diff: 60.0

**Comment by kharoc** [comment]
1 RAL

========================================================
FAILED TESTS                                                                                                                                 
========================================================                                                                                     
Empty DataFrame
Columns: [index, TestId]
Index: []
*******************************************************************************
TOTAL SUMMARY for test suite: 
PASSED: 1290/1290
FAILED: 0/1290
CRASH: 0/1290
TOTAL: 1290
MAX DELTA: 48.0
*******************************************************************************
Aggregations without group by:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Coalesce:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Column Basis:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Common Table Expressions:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Count without group by:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Date:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Timestamp:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Full outer join:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Group by:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Group by without aggregations:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Inner join:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Left outer join:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Non-EquiJoin Queries:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Nested Queries:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Order by:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Predicates With Nulls:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Simple String:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Unary ops:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Unify Tables:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Union:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Limit:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Where clause:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Bindable Alias:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Boolean:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Case:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Cast:   Start Mem: 8059.875   End Mem: 8059.875   Diff: 0.0
Concat:   Start Mem: 8059.875   End Mem: 8107.875   Diff: 48.0
Literal:   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0
Dir:   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0
File System Local:   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0
File System S3:   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0
File System Google Storage :   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0
Like:   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0
Substring:   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0
Wild Card:   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0
TPCH Queries:   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0
Round:   Start Mem: 8107.875   End Mem: 8107.875   Diff: 0.0

2 Worker's

========================================================
FAILED TESTS                                                                                                                                                           
========================================================                                                                                                               
Empty DataFrame
Columns: [index, TestId]
Index: []
*******************************************************************************
TOTAL SUMMARY for test suite: 
PASSED: 1489/1489
FAILED: 0/1489
CRASH: 0/1489
TOTAL: 1489
MAX DELTA: 395.0
*******************************************************************************
Aggregations without group by:   Start Mem: 748.875   End Mem: 1143.875   Diff: 395.0
Coalesce:   Start Mem: 1143.875   End Mem: 1171.875   Diff: 28.0
Common Table Expressions:   Start Mem: 1171.875   End Mem: 1163.875   Diff: -8.0
Count without group by:   Start Mem: 1163.875   End Mem: 1163.875   Diff: 0.0
Date:   Start Mem: 1163.875   End Mem: 1169.875   Diff: 6.0
Timestamp:   Start Mem: 1169.875   End Mem: 1169.875   Diff: 0.0
Full outer join:   Start Mem: 1169.875   End Mem: 1169.875   Diff: 0.0
Group by:   Start Mem: 1169.875   End Mem: 1187.875   Diff: 18.0
Group by without aggregations:   Start Mem: 1187.875   End Mem: 1187.875   Diff: 0.0
Inner join:   Start Mem: 1187.875   End Mem: 1191.875   Diff: 4.0
Left outer join:   Start Mem: 1191.875   End Mem: 1191.875   Diff: 0.0
Non-EquiJoin Queries:   Start Mem: 1191.875   End Mem: 1205.875   Diff: 14.0
Nested Queries:   Start Mem: 1205.875   End Mem: 1205.875   Diff: 0.0
Order by:   Start Mem: 1205.875   End Mem: 1207.875   Diff: 2.0
Predicates With Nulls:   Start Mem: 1207.875   End Mem: 1213.875   Diff: 6.0
Simple String:   Start Mem: 1213.875   End Mem: 1213.875   Diff: 0.0
Unary ops:   Start Mem: 1487.875   End Mem: 1485.875   Diff: -2.0
Unify Tables:   Start Mem: 1485.875   End Mem: 1485.875   Diff: 0.0
Union:   Start Mem: 1485.875   End Mem: 1445.875   Diff: -40.0
Limit:   Start Mem: 1445.875   End Mem: 1231.875   Diff: -214.0
Where clause:   Start Mem: 1231.875   End Mem: 1231.875   Diff: 0.0
Bindable Alias:   Start Mem: 1231.875   End Mem: 1247.875   Diff: 16.0
Boolean:   Start Mem: 1247.875   End Mem: 1247.875   Diff: 0.0
Case:   Start Mem: 1247.875   End Mem: 1251.875   Diff: 4.0
Cast:   Start Mem: 1251.875   End Mem: 1263.875   Diff: 12.0
Concat:   Start Mem: 1263.875   End Mem: 1381.875   Diff: 118.0
Literal:   Start Mem: 1381.875   End Mem: 1381.875   Diff: 0.0
Dir:   Start Mem: 1381.875   End Mem: 1683.875   Diff: 302.0
File System Local:   Start Mem: 1683.875   End Mem: 1427.875   Diff: -256.0
File System S3:   Start Mem: 1427.875   End Mem: 1427.875   Diff: 0.0
File System Google Storage :   Start Mem: 1427.875   End Mem: 1427.875   Diff: 0.0
Like:   Start Mem: 1427.875   End Mem: 1657.875   Diff: 230.0
Substring:   Start Mem: 1463.875   End Mem: 1439.875   Diff: -24.0
Wild Card:   Start Mem: 1439.875   End Mem: 1465.875   Diff: 26.0
TPCH Queries:   Start Mem: 1465.875   End Mem: 1471.875   Diff: 6.0
Round:   Start Mem: 1471.875   End Mem: 1471.875   Diff: 0.0
