### PR TITLE
[REVIEW] multiple columns inside COUNT() statement

### LINKED ISSUE #1403: [BUG] E2E test groupBy 08 fails with nulls
#QUERY:
SELECT count(distinct l_partkey, l_suppkey)
                    FROM lineitem
                    GROUP BY l_partkey, l_suppkey

Different values

FAILED TESTS
========================================================
  TestGroup InputType Result   TestId
0  Group by       gdf   Fail  TEST_08
1  Group by       orc   Fail  TEST_08
2  Group by   parquet   Fail  TEST_08
3  Group by       psv   Fail  TEST_08
```

### PR DESCRIPTION
**Pull request by Christian8491**
* This PR closes #1403
* This PR also enables queries containing multiple columns to just one count expression:  `COUNT(col_x, col_y) ` with and without nulls.
* This PR also fix a small issue related to tests in FULL mode using spark engine as comparator. 
* This PR also fix a small issue related to tests in GENERATOR mode. 
* PR https://github.com/BlazingDB/blazingsql-testing-files/pull/33 should be merged once this one will be merged.

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

**Comment by Christian8491** [comment]
rerun tests

**Comment by Christian8491** [comment]
rerun tests

File: engine/src/operators/GroupBy.cpp [hunk 1]
```diff
@@ -214,28 +213,44 @@ std::unique_ptr<ral::frame::BlazingTable> compute_groupby_without_aggregations(
...
-			CudfColumnView aggregation_input;
-			if(is_var_column(aggregation_input_expressions[i]) || is_number(aggregation_input_expressions[i])) {
-				aggregation_input = table.view().column(get_index(aggregation_input_expressions[i]));
+			cudf::column_view aggregation_input;
+
+			// For operations like `COUNT($0, $1)`
+			size_t num_columns_to_count = StringUtil::findAndCountAllMatches(agg_input_expr, "$");
+			if (num_columns_to_count > 1 && aggregation_types[i] == AggregateKind::COUNT_VALID) {
+				is_multi_var = true;
+				all_indices = get_all_indices_from_count_expression(agg_input_expr);
```
Comment (williamBlazing) [inline engine/src/operators/GroupBy.cpp:240]: I think you should combine `get_all_indices_from_count_expression` and `expand_indices_to_apply_casts` into one function. They are only ever used here, so it would make more sense to combine them and call the function something very explicit to this very purpose. Something like:
`modify_multi_column_count_expression`

**Review by williamBlazing — CHANGES_REQUESTED** [review]

File: engine/src/operators/GroupBy.cpp [hunk 2]
```diff
@@ -214,28 +213,44 @@ std::unique_ptr<ral::frame::BlazingTable> compute_groupby_without_aggregations(
...
 			reductions.emplace_back(std::move(scalar));
 		} else {
 			std::vector<std::unique_ptr<ral::frame::BlazingColumn>> aggregation_input_scope_holder;
-			CudfColumnView aggregation_input;
-			if(is_var_column(aggregation_input_expressions[i]) || is_number(aggregation_input_expressions[i])) {
-				aggregation_input = table.view().column(get_index(aggregation_input_expressions[i]));
+			cudf::column_view aggregation_input;
+
+			// For operations like `COUNT($0, $1)`
+			size_t num_columns_to_count = StringUtil::findAndCountAllMatches(agg_input_expr, "$");
```
[the remark this answers is not in the document]
Comment (Christian8491) [reply engine/src/operators/GroupBy.cpp:237]: At this point  `agg_input_expr` doesn't contain `COUNT(`    nor    `)`   expressions. At this level is something like  `$0, $1`

File: engine/src/operators/GroupBy.cpp (hunk 1 above)
Comment (Christian8491) [reply engine/src/operators/GroupBy.cpp:240]: ok, got it.
