### PR TITLE
[REVIEW] Implement string LEFT and RIGHT

### LINKED ISSUE #1174: [FEA] Support LEFT and RIGHT for strings
I'd like to be able to call LEFT (RIGHT) on a string column to slice the first (last) `N` characters of every string. This is listed as a supported operation on string columns in the Calcite reference, but it may need to be enabled based on [this](https://calcite.apache.org/docs/reference.html#dialect-specific-operators) segment of the docs describing Dialect specific operators.

```python
from pyspark.sql import SparkSession
from blazingsql import BlazingContext
import pandas as pd
​
​
# spark = SparkSession.builder \
#     .master("local") \
#     .getOrCreate()
​
# bc = BlazingContext()
​
​
df = pd.DataFrame({
    "a": ["Felipe", "William", "Rodrigo"],
    "b": [10, 9, 8],
})
​
bc.create_table("df", df)
sdf = spark.createDataFrame(df)
sdf.createOrReplaceTempView("df")
​
query = """
SELECT
    a,
    LEFT(a, 3)
FROM df
"""
​
spark.sql(query).show()
​
print(bc.explain(query)) # fails
# print(bc.sql(query)) # hangs
+-------+---------------+
|      a|left(df.`a`, 3)|
+-------+---------------+
| Felipe|            Fel|
|William|            Wil|
|Rodrigo|            Rod|
+-------+---------------+

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in com.blazingdb.calcite.application.RelationalAlgebraGenerator.getRelationalAlgebraString()

/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in com.blazingdb.calcite.application.RelationalAlgebraGenerator.getRelationalAlgebra()

/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in com.blazingdb.calcite.application.RelationalAlgebraGenerator.getNonOptimizedRelationalAlgebra()

/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/_jpype.cpython-37m-x86_64-linux-gnu.so in com.blazingdb.calcite.application.RelationalAlgebraGenerator.validateQuery()

Exception: Java Exception

The above exception was the direct cause of the following exception:

com.blazingdb.calcite.application.SqlValidationExceptionTraceback (most recent call last)
/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/pyblazing/apiv2/context.py in explain(self, sql)
   1693         try:
-> 1694             algebra = self.generator.getRelationalAlgebraString(sql)
   1695 

com.blazingdb.calcite.application.SqlValidationException: com.blazingdb.calcite.application.SqlValidationException: No match found for function signature LEFT(<CHARACTER>, <NUMERIC>)

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-21-9d2a7d09126d> in <module>
     29 spark.sql(query).show()
     30 
---> 31 print(bc.explain(query)) # fails
     32 # print(bc.sql(query)) # hangs

/raid/nicholasb/miniconda3/envs/rapids-tpcxbb-20201118/lib/python3.7/site-packages/pyblazing/apiv2/context.py in explain(self, sql)
   1696         except SqlValidationExceptionClass as exception:
   1697             # jpype.JException as exception:
-> 1698             raise Exception(exception.message())
   1699             # algebra = ""
   1700             # print("SQL Parsing Error")

Exception: No match found for function signature LEFT(<CHARACTER>, <NUMERIC>)
```

### PR DESCRIPTION
**Pull request by beckernick**
This PR:
- [x] Implements the LEFT and RIGHT ops for string columns using cudf::strings::slice_strings and cudf::binary_operation
- [x] Adds a new end-to-end test in stringsTests.py
- [x] Passes tests locally
- [x] PR to update testing files

This closes #1174

### CODE REVIEW

**Comment by GPUtester** [comment]
Please update the changelog in order to start CI tests.

View the gpuCI docs [here](https://docs.rapids.ai/gpuci#open-pr-or-update-pr).

File: engine/src/execution_graph/logic_controllers/LogicalProject.cpp [hunk 1]
```diff
@@ -132,6 +134,60 @@ std::unique_ptr<cudf::column> evaluate_string_functions(const cudf::table_view &
...
+            cudf::binary_operator::SUB,
+            cudf::data_type{cudf::type_id::INT32}
+        );
+
+        auto starting_positions_clamped = cudf::binary_operation(
+            starting_positions->view(),
+            cudf::make_column_from_scalar(cudf::numeric_scalar<int32_t>(0), table.num_rows())->view(),
+            cudf::binary_operator::NULL_MAX,
+            cudf::data_type{cudf::type_id::INT32}
+        );
```
Comment (beckernick) [inline engine/src/execution_graph/logic_controllers/LogicalProject.cpp:182]: This is using using a lot of memory, but I'm not sure of a better way to do this (as I don't know libcudf that well).

As an example, for `RIGHT(col, 5)`, we need to make sure that we're taking the last 5 characters of every string. Since strings have different lengths, I first calculate the string lengths and then subtract 5 from all of them to get the "correct" starting point for each string. Then, since this value can be negative (e.g., a string of length 3), I take the MAX of that column and a column of all 0. Then, this gets passed as the `start` to `slice_strings`.

Would love some feedback from folks on whether this makes sense, and if there may be a better approach.

cc @davidwendt if you have any bandwidth

Comment (davidwendt) [reply engine/src/execution_graph/logic_controllers/LogicalProject.cpp:182]: You should be able to just use `cudf::strings::slice_strings()` with a negative start value to slice from the right. 
Try this:
```
computed_col = cudf::strings::slice_strings( column, -offset );
```

Comment (beckernick) [reply engine/src/execution_graph/logic_controllers/LogicalProject.cpp:182]: Wow, perfect. For some reason when I tried this locally it wasn't working. I must have been making an unrelated mistake. 

Thanks David!

**Comment by beckernick** [comment]
https://github.com/BlazingDB/blazingsql-testing-files/pull/6

**Comment by williamBlazing** [comment]
rerun tests

**Comment by williamBlazing** [comment]
rerun-tests

**Comment by williamBlazing** [comment]
rerun tests
